name: test-run

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch or tag) to run against default to UI Ref"
        required: false
        default: ""

permissions:
  contents: read

jobs:
  build-run-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (honor manual 'ref' if provided)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/counter-service:test

      - name: Run container (bridge network)
        run: |
          docker rm -f counter-service || true
          docker run -d --name counter-service --network bridge -p 8080:80 local/counter-service:test

      - name: Health check (retry for readiness)
        shell: bash
        run: |
          set -euo pipefail
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz || true)
            if [ "$code" = "200" ]; then
              echo "Health check passed"
              exit 0
            fi
            echo "Waiting for app... ($i/30) got $code"
            sleep 2
          done
          echo "Health check FAILED"
          docker logs counter-service || true
          exit 1

      - name: Show logs
        if: failure()
        run: docker logs counter-service || true

      - name: Stop container
        if: always()
        run: docker rm -f counter-service || true
